# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Job Readiness' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~>5.4'
  pod 'AlamofireImage', '~>4.1'

  target 'Job ReadinessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Job ReadinessUITests' do
    # Pods for testing
  end

end
